POST http://localhost:8070/topic/aaa

POST http://localhost:8070/message/aaa

Ahora de nuevo 3

GET http://localhost:8072/aaa

curl -X POST http://localhost/message/ddd
-d Veamos

curl -X GET http://localhost/ddd

curl -X POST http://localhost/topic/primertopico

curl -X POST http://localhost/message/primertopico
-d "Primer mensaje enviado y mas"

curl -X GET http://localhost/primertopico